### ISSUE TITLE
Add RSS feed for blog

### ISSUE THREAD

**Issue by jamesharr** [fyne-io/fyne-io.github.io#16]
It would be nice to have an RSS feed along with you appropriate meta tags on the site so that RSS readers can locate the feed.

**Comment by andydotxyz** [comment]
The feed at https://fyne.io/feed.xml should work. I have added a link to it in the page header now so it's easier to find.

Does that work as you expected?

**Comment by jamesharr** [comment]
Awesome, Yes it does!

Feedly finds it when searching for "fyne.io" or even just "fyne"
