### ISSUE TITLE
Website favicon is not displayed

### ISSUE THREAD

**Issue by JRI98** [fyne-io/fyne-io.github.io#62]
When visiting the website, the favicon is not displayed.
![Screenshot 2024-08-30 at 14 35 34](https://github.com/user-attachments/assets/2ed40470-2e51-4893-a954-a195761fd052)
Upon further inspection, it is returning 404 when accessing `https://fyne.io/favicon.ico?1=`.

Compare with the docs website.
![Screenshot 2024-08-30 at 14 36 01](https://github.com/user-attachments/assets/8686a6dc-7aa9-4ba2-95b4-6c96fe8bb89f)

**Comment by andydotxyz** [comment]
Thanks for reporting, seems like there was a duplication when the theme was moved to a different template
